title: ""
description: ""
baseurl: "" 
url: "https://xi717.github.io"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
