title: ""
description: ""
minimal_mistakes_skin: "mint" 
baseurl: "" 
url: "https://xi717.github.io"
 
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache
  
defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false
