title: ""
description: ""
baseurl: ""
url: "https://xi717.github.io"

remote_theme: "mmistakes/minimal-mistakes"

show_excerpts: false
paginate: false
paginate_path: /page:num/

plugins:
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false
      sidebar: false
